begin;

create table public.clientes_comerciales (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  codigo text not null,
  nombre text not null,
  documento text,
  telefono text,
  email text,
  direccion text,
  limite_credito numeric(14,2) not null default 0 check (limite_credito >= 0),
  dias_credito integer not null default 0 check (dias_credito between 0 and 365),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (empresa_id, codigo),
  unique (id, empresa_id)
);

create table public.ventas_huevos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  numero bigint generated by default as identity,
  cliente_id uuid,
  cliente_nombre text not null,
  fecha date not null default current_date,
  tipo_venta text not null default 'CONTADO' check (tipo_venta in ('CONTADO','CREDITO')),
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  descuento numeric(14,2) not null default 0 check (descuento >= 0),
  total numeric(14,2) not null default 0 check (total >= 0),
  estado text not null default 'BORRADOR' check (estado in ('BORRADOR','CONFIRMADA','ANULADA')),
  observaciones text,
  registrado_por uuid default auth.uid() references auth.users(id) on delete set null,
  confirmada_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  foreign key (cliente_id, empresa_id) references public.clientes_comerciales(id, empresa_id) on delete restrict,
  unique (id, empresa_id)
);

create table public.venta_huevos_detalles (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  venta_id uuid not null,
  presentacion_id uuid not null,
  categoria text not null check (categoria in ('JUMBO','EXTRA_GRANDE','GRANDE','MEDIANO','PEQUENO','INDUSTRIAL')),
  cantidad_empaques integer not null check (cantidad_empaques > 0),
  unidades_por_empaque integer not null check (unidades_por_empaque > 0),
  unidades_totales integer not null check (unidades_totales > 0),
  precio_unitario numeric(14,2) not null check (precio_unitario >= 0),
  subtotal numeric(14,2) not null check (subtotal >= 0),
  created_at timestamptz not null default now(),
  foreign key (venta_id, empresa_id) references public.ventas_huevos(id, empresa_id) on delete cascade,
  foreign key (empresa_id, presentacion_id) references public.presentaciones_huevos(empresa_id, id) on delete restrict,
  unique (id, empresa_id)
);

alter table public.movimientos_inventario_huevos
  drop constraint if exists movimientos_inventario_huevos_empaque_id_key,
  alter column empaque_id drop not null,
  add column if not exists venta_detalle_id uuid,
  add column if not exists movimiento_origen_id uuid,
  add column if not exists referencia text;

alter table public.movimientos_inventario_huevos
  drop constraint if exists movimientos_inventario_huevos_tipo_check,
  add constraint movimientos_inventario_huevos_tipo_check check (tipo in ('ENTRADA_EMPAQUE','SALIDA_VENTA','REVERSO_VENTA')),
  add constraint movimientos_venta_detalle_fkey foreign key (venta_detalle_id, empresa_id) references public.venta_huevos_detalles(id, empresa_id) on delete restrict,
  add constraint movimientos_origen_fkey foreign key (movimiento_origen_id) references public.movimientos_inventario_huevos(id) on delete restrict;

create unique index movimientos_entrada_empaque_unique on public.movimientos_inventario_huevos(empaque_id) where tipo='ENTRADA_EMPAQUE';
create index ventas_empresa_fecha_idx on public.ventas_huevos(empresa_id, fecha desc) where deleted_at is null;
create index venta_detalles_venta_idx on public.venta_huevos_detalles(venta_id);
create index movimientos_salida_venta_idx on public.movimientos_inventario_huevos(venta_detalle_id) where tipo='SALIDA_VENTA' and estado='ACTIVO';

create or replace function private.avicola_preparar_detalle_venta()
returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_pres public.presentaciones_huevos%rowtype;
begin
  select * into v_pres from public.presentaciones_huevos where id=new.presentacion_id and empresa_id=new.empresa_id and activo=true and deleted_at is null;
  if not found then raise exception 'La presentación no existe o no está activa.' using errcode='23503'; end if;
  new.unidades_por_empaque := v_pres.unidades_por_empaque;
  new.unidades_totales := new.cantidad_empaques * v_pres.unidades_por_empaque;
  new.subtotal := round(new.cantidad_empaques * new.precio_unitario, 2);
  return new;
end;$$;

create trigger venta_detalle_preparar_trg before insert or update of empresa_id,presentacion_id,cantidad_empaques,precio_unitario on public.venta_huevos_detalles for each row execute function private.avicola_preparar_detalle_venta();

create or replace function public.avicola_confirmar_venta(p_venta_id uuid)
returns void language plpgsql security definer set search_path=public,private,pg_temp as $$
declare
  v_venta public.ventas_huevos%rowtype;
  v_det public.venta_huevos_detalles%rowtype;
  v_mov record;
  v_pendiente integer;
  v_tomar integer;
  v_subtotal numeric(14,2);
begin
  select * into v_venta from public.ventas_huevos where id=p_venta_id for update;
  if not found then raise exception 'Venta no encontrada.' using errcode='23503'; end if;
  if not exists (select 1 from public.empresa_usuarios eu where eu.empresa_id=v_venta.empresa_id and eu.usuario_id=auth.uid() and eu.activo=true and eu.rol in ('propietario','administrador','supervisor','ventas')) then raise exception 'No autorizado.' using errcode='42501'; end if;
  if v_venta.estado <> 'BORRADOR' then raise exception 'Solo se pueden confirmar ventas en borrador.' using errcode='23514'; end if;
  if v_venta.fecha > current_date then raise exception 'No se permiten ventas con fecha futura.' using errcode='23514'; end if;
  if not exists (select 1 from public.venta_huevos_detalles d where d.venta_id=v_venta.id) then raise exception 'La venta no tiene productos.' using errcode='23514'; end if;

  for v_det in select * from public.venta_huevos_detalles where venta_id=v_venta.id order by id loop
    v_pendiente := v_det.unidades_totales;
    for v_mov in
      select m.id,m.clasificacion_id,m.presentacion_id,m.lote_id,m.fecha,m.categoria,
             (m.unidades - coalesce((select sum(abs(s.unidades)) from public.movimientos_inventario_huevos s where s.movimiento_origen_id=m.id and s.tipo='SALIDA_VENTA' and s.estado='ACTIVO'),0))::integer as disponible
      from public.movimientos_inventario_huevos m
      where m.empresa_id=v_venta.empresa_id and m.tipo='ENTRADA_EMPAQUE' and m.estado='ACTIVO'
        and m.presentacion_id=v_det.presentacion_id and m.categoria=v_det.categoria
      order by m.fecha,m.created_at,m.id
      for update
    loop
      exit when v_pendiente <= 0;
      if v_mov.disponible <= 0 then continue; end if;
      v_tomar := least(v_pendiente,v_mov.disponible);
      insert into public.movimientos_inventario_huevos(empresa_id,empaque_id,clasificacion_id,presentacion_id,lote_id,fecha,categoria,tipo,cantidad_empaques,unidades,estado,venta_detalle_id,movimiento_origen_id,referencia)
      values(v_venta.empresa_id,null,v_mov.clasificacion_id,v_mov.presentacion_id,v_mov.lote_id,v_venta.fecha,v_mov.categoria,'SALIDA_VENTA',0,-v_tomar,'ACTIVO',v_det.id,v_mov.id,'Venta #'||v_venta.numero);
      v_pendiente := v_pendiente-v_tomar;
    end loop;
    if v_pendiente > 0 then raise exception 'Inventario insuficiente para % / presentación solicitada. Faltan % unidades.',v_det.categoria,v_pendiente using errcode='23514'; end if;
  end loop;

  select coalesce(sum(subtotal),0) into v_subtotal from public.venta_huevos_detalles where venta_id=v_venta.id;
  update public.ventas_huevos set subtotal=v_subtotal,total=greatest(v_subtotal-descuento,0),estado='CONFIRMADA',confirmada_at=now(),updated_at=now() where id=v_venta.id;
end;$$;

alter table public.clientes_comerciales enable row level security;
alter table public.ventas_huevos enable row level security;
alter table public.venta_huevos_detalles enable row level security;

create policy clientes_comerciales_select on public.clientes_comerciales for select to authenticated using (exists(select 1 from public.empresa_usuarios eu where eu.empresa_id=clientes_comerciales.empresa_id and eu.usuario_id=auth.uid() and eu.activo));
create policy clientes_comerciales_write on public.clientes_comerciales for all to authenticated using (exists(select 1 from public.empresa_usuarios eu where eu.empresa_id=clientes_comerciales.empresa_id and eu.usuario_id=auth.uid() and eu.activo and eu.rol in ('propietario','administrador','supervisor','ventas'))) with check (exists(select 1 from public.empresa_usuarios eu where eu.empresa_id=clientes_comerciales.empresa_id and eu.usuario_id=auth.uid() and eu.activo and eu.rol in ('propietario','administrador','supervisor','ventas')));
create policy ventas_select on public.ventas_huevos for select to authenticated using (exists(select 1 from public.empresa_usuarios eu where eu.empresa_id=ventas_huevos.empresa_id and eu.usuario_id=auth.uid() and eu.activo));
create policy ventas_insert on public.ventas_huevos for insert to authenticated with check (exists(select 1 from public.empresa_usuarios eu where eu.empresa_id=ventas_huevos.empresa_id and eu.usuario_id=auth.uid() and eu.activo and eu.rol in ('propietario','administrador','supervisor','ventas')));
create policy ventas_update on public.ventas_huevos for update to authenticated using (estado='BORRADOR' and exists(select 1 from public.empresa_usuarios eu where eu.empresa_id=ventas_huevos.empresa_id and eu.usuario_id=auth.uid() and eu.activo and eu.rol in ('propietario','administrador','supervisor','ventas'))) with check (exists(select 1 from public.empresa_usuarios eu where eu.empresa_id=ventas_huevos.empresa_id and eu.usuario_id=auth.uid() and eu.activo and eu.rol in ('propietario','administrador','supervisor','ventas')));
create policy venta_detalles_select on public.venta_huevos_detalles for select to authenticated using (exists(select 1 from public.empresa_usuarios eu where eu.empresa_id=venta_huevos_detalles.empresa_id and eu.usuario_id=auth.uid() and eu.activo));
create policy venta_detalles_write on public.venta_huevos_detalles for all to authenticated using (exists(select 1 from public.ventas_huevos v join public.empresa_usuarios eu on eu.empresa_id=v.empresa_id where v.id=venta_huevos_detalles.venta_id and v.estado='BORRADOR' and eu.usuario_id=auth.uid() and eu.activo and eu.rol in ('propietario','administrador','supervisor','ventas'))) with check (exists(select 1 from public.ventas_huevos v join public.empresa_usuarios eu on eu.empresa_id=v.empresa_id where v.id=venta_huevos_detalles.venta_id and v.estado='BORRADOR' and eu.usuario_id=auth.uid() and eu.activo and eu.rol in ('propietario','administrador','supervisor','ventas')));

grant select,insert,update on public.clientes_comerciales,public.ventas_huevos,public.venta_huevos_detalles to authenticated;
grant delete on public.venta_huevos_detalles to authenticated;
grant execute on function public.avicola_confirmar_venta(uuid) to authenticated;
revoke all on function private.avicola_preparar_detalle_venta() from public,anon;

commit;
